---
title: "Intruduction"
format: html
editor: visual
---


# Intro

Histoire de la datviz. La carto + la data viz => la geoviz.
Apparition des ordi.
Du web, .
...

# Intro

Ce qu'on va faire. Apprendre à faire des cartes animés et interactives avec Observable javascript et bertin.js dans Quarto. Ce qu'on ne va pas faire : apprendre à programmer en javascript

# Javascript

Historique du web Avant le web était statique Creation de js Pas créé au départ pour la visu de données. Avantages. Inconvénients. Les déboires du début. Langage qui peut être étendu. Wasm. D3.

# Observable javascript

C'est une société. C'est une plate-forme. Dans quarto

# Principes

## Les chunk ojs

## Les cellules et les variables

On définit les variables avec =

```{ojs}
//| echo: true
a = 10
b = 20
```

Ensuite, on peut utiliser ces variables pour faires des calculs

```{ojs}
//| echo: true
a + b
```


En Observable javascript, On peut ecrire le code dans n”importe quel ordre. On peut par exemple faire un calcul et définir les variables ensuite. 

```{ojs}
//| echo: true
c * d
c = 2
d = 17
```

C'est très déroutant mais extremement pratique. Car cela permet par exemple de positionner les figures au milieu d'un texte, et releguer tous les calculs dans une annexe technique à la fin du document. 

Cela à une implication. Chaque début de ligne doit définit une variable qui doit être unique. Si je crée 2 variables avec le même nom, le runtime d'Observable renvoit une erreur. 


```{ojs}
//| echo: true
e = "coucou"
e = "bonjour"
```

Mais on peut résoudre cela en utilisant des accolades. On retrouve alors le fonctionnement d'un code javascript normal.

```{ojs}
//| echo: true
{
let e = "coucou"
e = "bonjour"
return e
}
```






Ensuite, on peut utiliser ces variables pour faires des calculs



Chaque début de ligne définit une céllule qui doit être unique.

Attention, pas 2 fois le même nom de variable en début de ligne. On peut ecrire le code dans n"importe quel ordre, ce qui peut être déroutant.

On peut écrire du js avec des acolades Variables. Calculer. Fonction.

Oj n'est pas que javascript. C'est du js mais dans lequel on a ajouté des librairies. Présenter de, plot,...

C'est aussi des choses spécifiques.

# Import de données.

...

# Le format json

# Les inputs.

...

# C'est réactif.

Un exemple avec un cercle ou un rectangle.

Donc certes, le js n'est pas pensé à la base pour la dataviz, mais qui a été étendu pour cela et qui le sera encore.

Quarto est un environnement multi langage. Combiner R et ojs. Passer des données. Dans la pratique, on pour très bien utiliser R pour l'analyse de donnés et ojs pour la visualisation.

# Biblio sur la dataviz
